### ISSUE TITLE
Problem with capturing URL 

### ISSUE THREAD

**Issue by tanreeve** [Brisk-Apps/brisk#60]
Brisk  v2.0.0 
Brisk Browser Integration v. 1.1.2
Windows 11
Firefox

Hello, I try to download rar file from 1fichier.com but it's downloaded as a file without extension/File format. for example :
I have this [test.rar](https://1fichier.com/?o98n2n2wnsly2f6bw33f) but when downloaded the file become c969470637 without any extension/File format.

Using brisk 
![image](https://github.com/user-attachments/assets/a199bb1d-24e3-49ef-9e9b-aad0e0683e59)

Using httpdownloader 
![image](https://github.com/user-attachments/assets/e601d8dd-20d1-4e80-b9e2-980a5dd49aa7)

**Comment by AminBhst** [comment]
Hey.
This is a recurring issue with file sharing sites. It tries to download a redirected html instead of the file itself. I may have an idea on how to fix it. I'll update you in this issue when it's done. 
Thanks for the bug report!

**Comment by AminBhst** [comment]
Also relates to #28

**Comment by tanreeve** [comment]
> Also relates to #28 

Thank you for quick reply. 
I found another bug, when I try to download file attachments from certain forum post, I got "could not retrieve file information!" error and the file is downloaded with the browser instead. It seems like the browser extension doesn't capture the file URL.

![image](https://github.com/user-attachments/assets/e6dffd87-c163-465a-9509-9bcd9301355f)

**Comment by AminBhst** [comment]
Is it possible to send me a sample working download URL to test it myself?
This also just might be related to the same issue here. Especially if those attachments are only available to those who are logged in, i.e. with a valid session cookie.

**Comment by tanreeve** [comment]
This is the url for that file [log](https://fractalsoftworks.com/forum/index.php?action=dlattach;topic=18751.0;attach=12141)
from this forum link https://fractalsoftworks.com/forum/index.php?topic=18751.msg444447#msg444447

**Comment by AminBhst** [comment]
The first link requires a login and I couldn't find an attachment in second link. I suspect that this is only available for users who are logged in, so I think there is a high possibility that this issue will also be resolved since it probably suffers from the same problem you mentioned at the beginning of this issue.

**Comment by tanreeve** [comment]
and another file that have same issue is from bitbucket.org for example 
https://bitbucket.org/Histidine/space-janitor/downloads/SpaceJanitor_1.0.zip

**Comment by AminBhst** [comment]
> another file that have same issue is from bitbucket.org for example [bitbucket](https://bitbucket.org/Histidine/space-janitor/downloads/SpaceJanitor_1.0.zip)
> 
> and file from dropbox.com , in the download pop up it says that the file is 0 bytes, even though the file is more than 1 mb. link for dropbox file : [dropbox](https://www.dropbox.com/scl/fi/tgfw7i0xcyon2kpaywieh/Terrain-Mod-v3.4-Dark-Blue-Water.zip?rlkey=ps6a508zrt4g84df6sxflyqxf&e=3&dl=0)

The first one was interesting. Apparently the server outright rejects all HEAD requests with a 203 forbidden status. Weird edge-case but I guess I'll add a fallback to GET if HEAD requests failed and it should solve that problem easily. Thanks for that it was really helpful. I didn't know some servers rejected HEAD requests.

The second link though I didn't find a problem with. I tested a few files and it was fine. Which file in particular were you trying to download?

**Comment by AminBhst** [comment]
Were you logged in when downloading from that dropbox link by any chance? Could you also try downloading without being logged in?

**Comment by tanreeve** [comment]
> Were you logged in when downloading from that dropbox link by any chance? Could you also try downloading without being logged in? Because if that's the case, it's literally the same issue that exists with google drive.

I was not logged into Dropbox when I encountered this issue. I tried logging in and downloading the file, but I still get this issue:

![image](https://github.com/user-attachments/assets/a61d1bef-ca47-471c-b650-4e422056e776)

**Comment by AminBhst** [comment]
> > Were you logged in when downloading from that dropbox link by any chance? Could you also try downloading without being logged in? Because if that's the case, it's literally the same issue that exists with google drive.
> 
> I was not logged into Dropbox when I encountered this issue. I tried logging in and downloading the file, but I still get this issue:
> 
> ![image](https://private-user-images.githubusercontent.com/114658849/380429581-a61d1bef-ca47-471c-b650-4e422056e776.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTM3NDYsIm5iZiI6MTcyOTk1MzQ0NiwicGF0aCI6Ii8xMTQ2NTg4NDkvMzgwNDI5NTgxLWE2MWQxYmVmLWNhNDctNDcxYy1iNjUwLTRlNDIyMDU2ZTc3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxNDM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFlNTdlOWY5NmRmZjcxNWFjNTg4MzUwZTcxNjlhNzE0ZGFhY2ZhYTlmNTQyNzYzNjU2MjRmMjQ4NTNiMTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.erFYtSXQEUloABJkKMMgIBfx4YQ1W_bJDeNS28nMbSg)

Which file is this one exactly? Could you send me its name and path in dropbox?

**Comment by AminBhst** [comment]
Makes sense. dropbox also rejects HEAD requests. This issue will also be fixed by a fallback to GET request. 
I did some research for the first link of this issue (the TEST.rar file) and it wasn't what I thought it was. I'm not sure but I think before the extension captures the download, the browser has already sent a requests and therefore, the link is already expired because their links only work once and need to be regenerated after each request. Idk if I can come up with a fix for that. But the other issues you had all go back to HEAD requests being rejected. 
I'll release an update that fixes this pretty soon. Thanks for bringing these to my attention.

**Comment by AminBhst** [comment]
@tanreeve [v2.0.1](https://github.com/AminBhst/brisk/releases/tag/v2.0.1) is released with a fix for this. Tested it out myself and it worked. Try it out and let me know if you still have issues. I will close this issue for now but will reopen it if necessary. 
Thanks for letting me know about these bugs.

**Comment by AminBhst** [comment]
@tanreeve [v2.0.1](https://github.com/AminBhst/brisk/releases/tag/v2.0.1) is now available with a fix for that. Let me know if you faced any other issued. 
Thanks for letting me know about these bugs.

**Comment by AminBhst** [comment]
I'll check these out as well and see what I can come up with

**Comment by AminBhst** [comment]
Stale
